#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install wget
  case $(_os) in
    macos)
      # librime
      (
        cd /tmp
        wget --no-check-certificate $(get_github_latest_release_url 'rime/librime' 'osx\.zip') -O rime-osx.zip
        mkdir -p $XDG_CONFIG_HOME/emacs/librime
        unzip rime-osx.zip -d $XDG_CONFIG_HOME/fcitx/librime
        rm -rf rime-osx.zip
      )
      brew install --cask squirrel
      ;;
    linux-RHEL)
      # TODO
      ;;
    linux-arch)
      yay --needed --noconfirm -S fcitx fcitx-im fcitx-configtool librime fcitx-rime
      ;;
    linux-debian)
      sudo apt install fcitx fcitx-rime

      # docker build https://github.com/rime/librime.git -t librime
      # docker run -it librime bash && docker ps to lookup docker
      # container_id=<input the running container id>
      # sudo docker cp -L ${container_id}:/usr/lib/x86_64-linux-gnu/librime.so /usr/lib/
      # sudo docker cp -L ${container_id}:/usr/lib/x86_64-linux-gnu/librime.so.1 /usr/lib/
      # sudo docker cp -L ${container_id}:/usr/lib/x86_64-linux-gnu/librime.so.1.5.3 /usr/lib/
      ;;
  esac

  # Download zhwiki pinyin dictionary
  wget --no-check-certificate $(get_github_latest_release_url felixonmars/fcitx5-pinyin-zhwiki "\.dict\.yaml") \
    -O $XDG_CONFIG_HOME/fcitx/rime/zhwiki.dict.yaml

  # Install emoji
  mkdir -p /tmp/fcitx-install
  (
    cd /tmp/fcitx-install
    curl -fsSL https://git.io/rime-install | bash -s -- emoji
  )
  rm -rf /tmp/fcitx-install
}

# update() {}

link() {
  mkdir -p ${XDG_CONFIG_HOME}/fcitx

  # 1. System input method
  mklink $DOTTY_CONFIG_HOME/misc/chinese/config/fcitx/config ${XDG_CONFIG_HOME}/fcitx/config
  mklink $DOTTY_CONFIG_HOME/misc/chinese/config/fcitx/rime/* ${XDG_CONFIG_HOME}/fcitx/rime/
  [[ -d ${DOTTY_ASSETS_HOME}/rime-dictionaries ]] && mklink ${DOTTY_ASSETS_HOME}/rime-dictionaries/*.dict.yaml ${XDG_CONFIG_HOME}/fcitx/rime/
  mklink pam_environment ${HOME}/.pam_environment

  case $(_os) in
    macos)
      mklink ~/.config/fcitx/rime ~/Library/Rime
      ;;
  esac

  # 2. Emacs input method

  # Don't use ${XDG_CONFIG_HOME}/fcitx/rime as your emacs fcitx config dir. It will cause conflict.
  mklink $DOTTY_CONFIG_HOME/misc/chinese/config/fcitx/rime/* $XDG_CONFIG_HOME/fcitx/emacs-rime/
  [[ -d ${DOTTY_ASSETS_HOME}/rime-dictionaries ]] && mklink ${DOTTY_ASSETS_HOME}/rime-dictionaries/*.dict.yaml $XDG_CONFIG_HOME/fcitx/emacs-rime/

  local link_files=("opencc" "emoji_suggestion.yaml" "zhwiki.dict.yaml")
  for file in ${link_files[@]}; do
    mklink ${XDG_CONFIG_HOME}/fcitx/rime/$file $XDG_CONFIG_HOME/fcitx/emacs-rime/
  done

}

clean() {
  rm -rf ${XDG_CONFIG_HOME}/fcitx
}

init "$@"
