#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
  macos)
    brew install duti rga pandoc poppler tesseract ffmpeg imagemagick graphicsmagick
    brew install --cask dropbox neteasemusic webtorrent \
      jetbrains-toolbox typora iina keycastr discord zoomus \
      shadowsocksx google-backup-and-sync kap obs balenaEtcher

    brew install mas
    mas install 937984704  # Amphetamine
    mas install 695406827  # Dropzone 3
    mas install 441258766  # Magnet
    mas install 585829637  # Todoist
    mas install 1127253508 # DrUnarchiver
    mas install 1176895641 # Spark
    mas install 576338668  # Leaf
    mas install 747648890  # telegram
    mas install 836500024  # Wechat
    mas install 451108668  # QQ
    mas install 497799835  # Xcode

    # Set default apps
    ${0:A:h}/bin/macos_set_default_apps.sh
    ;;
  arch)
    yay --needed --noconfirm -S \
      telegram-desktop jetbrains-toolbox \
      dropbox webtorrent-desktop typora
    ;;

  # TODO: debian apps
  debian) # Insatll typora
    wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
    # add Typora's repository
    sudo add-apt-repository 'deb https://typora.io/linux ./'
    sudo apt-get update
    # install typora
    $APT_INSTALL typora
    ;;
  esac
  # NPM Packages
  npm install -g npm yarn prettier live-server hexo-cli \
    reveal-md typescript tslint cspell import-js

  # PIP
  python3 -m pip install --user --upgrade pylint yapf autoflake gnureadline black importmagic epc grip cpplint
}

# update() {}

link() {}

clean() {}

init "$@"
