#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
  macos)
    brew install duti rga pandoc poppler tesseract ffmpeg imagemagick graphicsmagick youtube-dl
    brew install --cask dropbox neteasemusic webtorrent \
      jetbrains-toolbox typora iina keycastr discord zoomus \
      clashx google-backup-and-sync kap obs balenaEtcher

    # Optional preview apps
    brew install suspicious-package apparency

    brew install mas
    mas install 1485052491 # Dropzone 4: https://aptonic.com/
    mas install 1127253508 # Unarchiver One: RAR & Zip Tool
    mas install 1176895641 # Spark
    mas install 576338668  # Leaf
    mas install 747648890  # telegram
    mas install 836500024  # Wechat
    mas install 451108668  # QQ
    mas install 497799835  # Xcode

    # Set default apps
    ${0:A:h}/bin/macos_set_default_apps.sh
    ;;
  linux-arch)
    yay --needed --noconfirm -S \
      telegram-desktop jetbrains-toolbox \
      dropbox webtorrent-desktop typora youtube-dl
    ;;
  linux-RHEL)
    # TODO
    ;;
  linux-debian)
    # TODO: debian apps
    # Insatll typora
    brew install youtube-dl
    wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
    # add Typora's repository
    sudo add-apt-repository 'deb https://typora.io/linux ./'
    sudo apt-get update
    # install typora
    $APT_INSTALL typora
    ;;
  esac
  # NPM Packages
  npm install -g npm yarn prettier live-server hexo-cli \
    reveal-md typescript tslint cspell import-js

  # PIP
  python3 -m pip install --user --upgrade pylint yapf autoflake gnureadline black importmagic epc grip cpplint
}

# update() {}

link() {}

clean() {}

init "$@"
