#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install rga pandoc poppler tesseract ffmpeg imagemagick graphicsmagick yt-dlp

  # Deploy rust if not yet deployed
  ! topic-enabled-p dev/python && dotty dev/python
  PIP3_INSTALL spotdl

  ! topic-enabled-p dev/node && ${0:A:h}/../../deploy dev/node
  npm install hexo-cli reveal-md

  case $(_os) in
    macos)
      brew install --cask appcleaner typora obsidian dropbox neteasemusic webtorrent \
        wpsoffice-cn keycastr discord zoomus clashx google-drive obs balenaEtcher

      echo-info "Install the following apps from App Store"
      echo-info "Dropzone 4, FastZip, iRightMouse, iShot, Spark, LyricsX, Leaf, Telegram, Wechat, QQ"

      # Set default apps
      $DOTTY_HOME/base/macos/macos_set_default_apps.sh $DOTTY_HOME/misc/private/macos_misc_default_apps.txt
      ;;
    linux-arch)
      yay --needed --noconfirm -S \
        telegram-desktop \
        dropbox webtorrent-desktop
      ;;
    linux-RHEL)
      ;;
    linux-debian)
      ;;
  esac

  # Install typora theme
  $DOTTY_CONFIG_HOME/misc/private/install_typora_themes.sh
}

# update() {}

link() {}

clean() {}

init "$@"
