#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
  linux-arch)
    yay --needed --noconfirm -S \
      xorg-server xorg-xrandr xorg-xinit xorg-xsetroot xorg-xbacklight xdotool wmname maim wmctrl \
      bspwm sxhkd compton dunst rofi feh xcb-proto polybar libnotify redshift pavucontrol \
      flat-remix-gnome flat-remix-gtk flat-remix qt5-styleplugins i3lock
    ;;
  linux-RHEL)
    # TODO: add RHEL bspwm packages
    ;;
  linux-debian)
    APT_INSTALL compton i3lock suckless-tools redshift xdotool xbacklight gcc make pavucontrol
    # 18 or 16
    if cat /etc/os-release | rg -q 16; then
      zsh ${0:A:h}/ubuntu-build-bspwm.sh
      zsh ${0:A:h}/ubuntu-build-polybar.sh
      brew install feh
    elif cat /etc/os-release | rg -q 18; then
      APT_INSTALL bspwm sxhkd dunst feh maim
      zsh ${0:A:h}/ubuntu-build-polybar.sh
    elif cat /etc/os-release | rg -q 20; then
      APT_INSTALL bspwm sxhkd polybar dunst feh maim
    fi
    ;;
  esac

  zsh $DOTTY_CONFIG_HOME/wm/general/install_white_sur_theme.sh
  zsh $DOTTY_CONFIG_HOME/wm/general/install_breeze_cursor.sh

  wget https://github.com/erebe/greenclip/releases/download/3.4/greenclip -O $XDG_BIN_HOME/greenclip
  chmod +x $XDG_BIN_HOME/greenclip
}

# update() {}

remove_configs() {
  # Remove configs from XDG_CONFIG_HOME
  dir=$1
  config_files=("${(@f)$(ls ${dir})}")

  for file in ${config_files[@]}; do
    rm -rf "$XDG_CONFIG_HOME/$file"
  done
}

link() {
  remove_configs $DOTTY_CONFIG_HOME/wm/bspwn/config
  remove_configs $DOTTY_CONFIG_HOME/wm/general/config
  mklink $DOTTY_CONFIG_HOME/wm/bspwn/config/* $XDG_CONFIG_HOME/
  mklink $DOTTY_CONFIG_HOME/wm/general/config/* $XDG_CONFIG_HOME/
}

clean() {
  remove_configs $DOTTY_CONFIG_HOME/wm/bspwm/config
  remove_configs $DOTTY_CONFIG_HOME/wm/general/config
}

init "$@"
