#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install go

  case $(_os) in
    # Ubuntu 18, AL2 needs gcc5 for dlv
    linux-*) brew install gcc@5;;
  esac
  go install github.com/ramya-rao-a/go-outline@latest
  go install github.com/cweill/gotests/gotests@latest
  go install github.com/fatih/gomodifytags@latest
  go install github.com/josharian/impl@latest
  go install github.com/haya14busa/goplay/cmd/goplay@latest
  go install golang.org/x/tools/gopls@latest
  go install github.com/go-delve/delve/cmd/dlv@latest
  go install honnef.co/go/tools/cmd/staticcheck@latest
}

# update() {}

# link() {}

# clean() {}

init "$@"
