#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install go

  go install github.com/ramya-rao-a/go-outline@latest
  go install github.com/josharian/impl@latest
  go install github.com/haya14busa/goplay/cmd/goplay@latest
  go install golang.org/x/tools/cmd/guru@latest
  go install golang.org/x/tools/gopls@latest
  go install github.com/go-delve/delve/cmd/dlv@latest
  go install honnef.co/go/tools/cmd/staticcheck@latest
  go install github.com/x-motemen/gore/cmd/gore@latest
  go install github.com/stamblerre/gocode@latest
  go install golang.org/x/tools/cmd/godoc@latest
  go install golang.org/x/tools/cmd/goimports@latest
  go install golang.org/x/tools/cmd/gorename@latest
  go install github.com/cweill/gotests/gotests@latest
  go install github.com/fatih/gomodifytags@latest
}

# update() {}

link() {
  rm -rf $XDG_CONFIG_HOME/dlv
  mklink $DOTTY_CONFIG_HOME/dev/go/config/* $XDG_CONFIG_HOME/
}

# clean() {}

init "$@"
