#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source ${0:A:h}/aliases.zsh

install() {
  case $(_os) in
  arch)
    yay --needed --noconfirm -S flat-remix-gnome flat-remix-gtk flat-remix

    sudo pacman -S gnome gnome-extra gdm manjaro-gnome-assets manjaro-gdm-theme manjaro-settings-manager
    ;;
  debian)
    sudo apt-get install -y gnome-shell ubuntu-gnome-desktop
    tempdir=/tmp/temp-install
    mkdir -p $tempdir
    # Flat-remix Theme
    (
      cd $tempdir
      wget --no-check-certificate $(get_github_latest_release_url 'daniruiz/flat-remix-gtk') -O flat-remix-gtk.tar.gz
      tar -zxvf flat-remix-gtk.tar.gz
      mkdir -p ~/.themes && cp -r flat-remix-gtk-*/Flat-Remix-GTK-* ~/.themes
      rm -rf $tempdir/flat-remix-gtk*

      wget --no-check-certificate $(get_github_latest_release_url 'daniruiz/flat-remix') -O flat-remix.tar.gz
      tar -zxvf flat-remix.tar.gz
      mkdir -p ~/.icons && cp -r flat-remix-*/Flat-Remix-* ~/.icons
      rm -rf $tempdir/flat-remix*
    )
    ;;
  esac

  sudo systemctl enable gdm.service --force

  # Setting themes
  gsettings set org.gnome.desktop.interface icon-theme "Flat-Remix-Blue"
  gsettings set org.gnome.desktop.interface cursor-theme 'xcursor-breeze-snow'
  gsettings set org.gnome.desktop.interface gtk-theme 'Flat-Remix-GTK-Blue'
  gsettings set org.gnome.shell.extensions.user-theme name 'Flat-Remix'
}

# update() {}

link() {
  dconf-load-gnome
}

clean() {}

init "$@"
