#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source $DOTTY_CONFIG_HOME/desktop/gnome/aliases.zsh

install() {
  case $(_os) in
  linux-arch)
    sudo pacman -S gdm gnome-extra gnome-shell gnome-tweaks
    ;;
  linux-RHEL)
    # TODO:
    ;;
  linux-debian)
    APT_INSTALL gdm3 gnome-session gnome-shell gnome-tweaks
  esac

  sudo systemctl enable gdm.service --force

  zsh $DOTTY_CONFIG_HOME/desktop/general/install_white_sur_theme.sh
  zsh $DOTTY_CONFIG_HOME/desktop/general/install_breeze_cursor.sh
  gsettings set org.gnome.desktop.interface cursor-theme 'xcursor-breeze-snow'
}

# update() {}

link() {
  dconf-load-gnome
}

clean() {}

init "$@"
