#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  brew install --cask iterm2
}

update() {
  brew upgrade --cask iterm2
}

link() {
  mklink com.googlecode.iterm2.plist $HOME/Library/Preferences/
}

clean() {
  rm -rfv $HOME/Library/Preferences/com.googlecode.iterm2.plist
  brew uninstall --cask iterm2
}

init "$@"
