#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
  macos)
    brew install pandoc ffmpeg glances bandwhich
    brew install --cask google-chrome forklift visual-studio-code bitwarden ticktick keepingyouawake

    # Vscode enable key-repeating
    defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false         # For VS Code
    defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false # For VS Code Insider
    defaults delete -g ApplePressAndHoldEnabled                                      # If necessary, reset global default
    ;;
  linux-arch)
    yay --needed --noconfirm -S \
      pandoc ffmpeg glances mimeo bandwhich \
      google-chrome visual-studio-code-bin

    mimeo --prefer google-chrome.desktop --prefer vlc.desktop
    ;;
  linux-RHEL)
    # TODO
    ;;
  linux-debian)
    brew install pandoc ffmpeg glances

    ${0:A:h}/../../deploy dev/rust
    cargo install bandwhich
    ;;
  esac
}

# update() {}

# link() {}

clean() {
  for f in $(echo .*); do
    rm -fv ~/$f
  done
}

init "$@"
