#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install pandoc ffmpeg \
      bandwhich \ # network monitor
      eva \ # bc: calculator

  brew tap clementtsang/bottom
  brew install bottom

  case $(_os) in
    macos)
      brew install --cask microsoft-edge iina ticktick keepingyouawake

      # Set iina as default music/video player
      $DOTTY_HOME/base/macos/macos_set_default_apps.sh $DOTTY_HOME/misc/apps/macos_iina_as_default_app.txt
      ;;
  esac
}

# update() {}

# link() {}

clean() {
  for f in $(echo .*); do
    rm -fv ~/$f
  done
}

init "$@"
