#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  # bandwhich: network monitor
  # eva: alternative bc, calculator
  # btop: better top
  brew install prettier pandoc ffmpeg bandwhich eva btop

  case $(_os) in
    macos)
      brew install --cask microsoft-edge iina ticktick keepingyouawake

      # Set iina as default music/video player
      $DOTTY_HOME/base/macos/macos_set_default_apps.sh $DOTTY_HOME/misc/apps/macos_iina_as_default_app.txt
      ;;
  esac
}

# update() {}

link() {
  mklink $DOTTY_CONFIG_HOME/misc/apps/.* ~/
  rm -rf $XDG_CONFIG_HOME/btop
  mklink $DOTTY_CONFIG_HOME/misc/apps/config/btop $XDG_CONFIG_HOME/
}

clean() {
  for f in $(echo $DOTTY_CONFIG_HOME/misc/app/.*); do
    rm -f ~/${f##*/}
  done
}

init "$@"
