#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  case $(_os) in
  macos | debian)
    brew install rustup
    ;;
  arch)
    yay --needed --noconfirm -S rustup
    ;;
  esac
  rustup-init -y
}

update() {
  rustup update
}

# link() {}

# clean() {}

init "$@"
