#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  brew install rustup
  rustup-init -y
}

update() {
  rustup update
}

# link() {}

clean() {
  rm -rf $CARGO_HOME $RUSTUP_HOME
}

init "$@"
