#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install rustup
  rustup-init -y
}

update() {
  rustup update
}

link() {}

clean() {
  brew uninstall rustup
  rm -rf $CARGO_HOME $RUSTUP_HOME
}

init "$@"
