#!/usr/bin/env zsh
icon=""
if [[ $1 == "1" ]]; then
    echo "%{F#555856}${icon}%{F-}"
    exit
fi

echo "%{F#555856}${icon}*%{F-}"

[[ -f /tmp/polybar-updates ]] && last=$(</tmp/polybar-updates)
check=$(yay -Pu | wc -l)
if [[ "$check" != "0" ]]; then
    echo "%{F#b5bd68}${icon}$pac+$aur%{F-}"
    if [[ $last != "$pac$aur" ]]; then
        notify-send "$((pac+aur)) updates available"
        ding updates
        echo "$pac$aur" >/tmp/polybar-updates
    fi
else
    echo "%{F#555856}${icon}%{F-}"
fi
