#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  brew install tmux xclip
  if [[ $(_os) == "macos" ]]; then
    brew install reattach-to-user-namespace
  fi

  _ensure_repo tmux-plugins/tpm $TMUX_PLUGIN_MANAGER_PATH/tpm

  # kill tmux to avoid protocol version mismatch (client 8, server 7) error
  pkill tmux || true

  local tpm=$TMUX_PLUGIN_MANAGER_PATH/tpm
  if [[ -d $tpm ]]; then
    $tpm/bin/install_plugins all
  fi
}

update() {
  local tpm=$TMUX_PLUGIN_MANAGER_PATH/tpm
  if [[ -d $tpm ]]; then
    $tpm/bin/update_plugins all
  fi
}

link() {
  mklink tmux.conf $TMUX_HOME/
}

clean() {
  rm -rfv $TMUX_HOME $TMUX_PLUGIN_MANAGER_PATH
}

init "$@"
