#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  case $(_os) in
  macos)
    brew install tmux reattach-to-user-namespace
    ;;
  arch)
    yay --needed --noconfirm -S tmux xclip
    ;;
  debian)
    brew install tmux xclip
    ;;
  esac

  _ensure_repo tmux-plugins/tpm $TMUX_PLUGINS_HOME/tpm

  if [[ -d $tpm ]]; then
    $tpm/bin/install_plugins all
  fi
}

update() {
  local tpm=$TMUX_PLUGINS_PATH/tpm
  if [[ -d $tpm ]]; then
    $tpm/bin/update_plugins all
    $tpm/bin/clean_plugins all
  fi

}

link() {
  mklink tmux*.conf $TMUX_HOME/
  mklink scripts $TMUX_HOME/scripts
}

clean() {
  rm -rfv $TMUX_HOME $TMUX_PLUGINS_HOME
}

init "$@"
