repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1
    hooks:
      - id: prettier
  - repo: https://github.com/awslabs/git-secrets
    rev: master
    hooks:
      - id: git-secrets
