#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install editorconfig
}

# update() {}

link() {
  mklink $DOTTY_CONFIG_HOME/editor/editorconfig/.editorconfig ~/.editorconfig
}

clean() {
  rm -fv ~/.editorconfig
}

init "$@"
