#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install stack ghc
  stack config set system-ghc --global true
  stack setup
}

update() {
  stack update
}

# link() {}

# clean() {}

init "$@"
