#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  brew install rbenv ruby-build
}

update() {
  brew upgrade rbenv ruby-build
}

link() {
  mklink config/irbrc $IRBRC
  mklink config/pryrc $PRYRC
}

clean() {
  rm -fv $IRBRC $PRYRC
  rmdir -v ${IRBRC%/*} ${PRYRC%/*}
  rm -rf $RBENV_ROOT
}

init "$@"
