#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install rbenv ruby-build
}

update() {
  brew upgrade rbenv ruby-build
}

link() {
  mklink $DOTTY_CONFIG_HOME/dev/ruby/config/irbrc $IRBRC
  mklink $DOTTY_CONFIG_HOME/dev/ruby/config/pryrc $PRYRC
}

clean() {
  rm -fv $IRBRC $PRYRC
  rmdir -v ${IRBRC%/*} ${PRYRC%/*}
  rm -rf $RBENV_ROOT
  rm -f $XDG_CACHE_HOME/${SHELL##*/}/rbenv
}

init "$@"
