#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install cmake ninja clang-format

  if [[ $(_os) == 'linux-*' ]]; then
    brew install llvm gdb
  fi
}

# update() {}

link() {
  mklink $DOTTY_CONFIG_HOME/dev/cc/lldb/.lldbinit ~/
}

# clean() {}

init "$@"
