#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install cmake ninja llvm cppcheck cpplint

  case $(_os) in
    linux-*)
      brew install gdb
      ;;
    macos)
      ln -s -f "$(brew --prefix llvm)/bin/clangd" "$HOMEBREW_PREFIX/bin/clangd"
      ln -s -f "$(brew --prefix llvm)/bin/clang-tidy" "$HOMEBREW_PREFIX/bin/clang-tidy"
      ln -s -f "$(brew --prefix llvm)/bin/clang-format" "$HOMEBREW_PREFIX/bin/clang-format"
      ;;
  esac
}

# update() {}

link() {
  mklink $DOTTY_CONFIG_HOME/dev/cc/lldb/.lldbinit ~/
  case $(_os) in
    linux-*) mklink $DOTTY_CONFIG_HOME/dev/cc/clangd/config.yaml $XDG_CONFIG_HOME/clangd/config.yaml ;;
    macos) mklink $DOTTY_CONFIG_HOME/dev/cc/clangd/config.yam ~/Library/Preferences/clangd/config.yaml ;;
  esac
}

# clean() {}

init "$@"
