#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "one"
    colorscheme_bg = "light"
    filetree_direction = "left"
    filemanager = "nerdtree"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    disabled_plugins = ["tmuxline.vim"]
    relativenumber = false

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'top'
    default_height = 30

[[layers]]
    name = "colorscheme"

[[layers]]
  name = "core#statusline"
  enable = false

[[layers]]
    name = "unite"

[[layers]]
    name = "ctrlp"

[[layers]]
    name = "tmux"

[[layers]]
    name = "lang#rust"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "format"

[[custom_plugins]]
    name = "francoiscabrol/ranger.vim"
    on_cmd = ["Ranger"]
    # note: you need to disable merged feature
    merged = false

[[custom_plugins]]
    name = "lilydjwg/colorizer"
    on_cmd = ["ColorHighlight", "ColorToggle"]
    merged = false
