#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
    macos)
      brew install koekeishiya/formulae/yabai koekeishiya/formulae/skhd
      ;;

  esac

}

# update() {}

link() {
  mklink $DOTTY_CONFIG_HOME/wm/yabai/config/* $XDG_CONFIG_HOME/
  mklink $DOTTY_CONFIG_HOME/wm/yabai/skhdrc ~/.skhdrc
}

clean() {
  yabai --stop-service
  yabai --uninstall-service
  sudo yabai --uninstall-sa

  # these are logfiles that may be created when running yabai as a service.
  rm -rf /tmp/yabai_$USER.out.log
  rm -rf /tmp/yabai_$USER.err.log

  # remove config and various temporary files
  rm -fv ~/.skhdrc $XDG_CONFIG_HOME/yabairc
  rm /tmp/yabai_$USER.lock
  rm /tmp/yabai_$USER.socket
  rm /tmp/yabai-sa_$USER.socket

  skhd --stop-service
  skhd --uninstall-service

  # unload the scripting addition by forcing a restart of Dock.app
  killall Dock

  brew uninstall yabai skhd
}

init "$@"
