#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
  macos)
    brew install asciinema
    ;;
  arch)
    yay --needed --noconfirm -S asciinema
    ;;
  debian)
    sudo apt-get install -y asciinema
    ;;
  esac
}

# update() {}

# link() {}

# clean() {}

init "$@"
