#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install unison

  # Deploy rust if not yet deployed
  ! topic-enabled-p dev/rust && dotty dev/rust

  cargo install unison-fsmonitor
  case $(_os) in
    macos)
      sudo sysctl kern.maxfiles=131072 kern.maxfilesperproc=65536
      sudo cat <<EOF | sudo tee -a /etc/sysctl.conf
kern.maxfiles=131072
kern.maxfilesperproc=65536
EOF
      ;;
    linux-*)
      sudo sysctl -w fs.inotify.max_user_watches=131072
      cat <<EOF | sudo tee -a /etc/sysctl.conf
fs.inotify.max_user_watches = 131072
EOF
      ;;
  esac
}

update() {
  brew upgrade unison
}

link() {
  mklink $DOTTY_CONFIG_HOME/misc/unison/default.prf ~/.unison/default.prf
}

clean() {
  brew uninstall unison
  rm -f ~/.unison/default.prf
}

init "$@"
