#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

_install_pip_packages() {
  PIP3_INSTALL pip setuptools

  # Other packages
  PIP3_INSTALL debugpy pdbpp autoflake gnureadline
}

install() {
  brew install pyright black poetry pylint ruff-lsp

  brew install python@3.11

  case $(_os) in
    macos)
      brew install miniconda
      ;;
    linux-*)
      (
        tempdir=/tmp/temp-install
        mkdir -p $tempdir
        cd $tempdir
        curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3*.sh -b -p $HOME/.miniconda
        rm -f $tempdir/Miniconda3*.sh
      )
      ;;
  esac

  _install_pip_packages
}

update() {
  _install_pip_packages
}

link() {
  mklink $DOTTY_CONFIG_HOME/dev/python/config/black $XDG_CONFIG_HOME/
  mklink $DOTTY_CONFIG_HOME/dev/python/config/flake8 $XDG_CONFIG_HOME/
  mklink $DOTTY_CONFIG_HOME/dev/python/config/pudb/pudb.cfg $XDG_CONFIG_HOME/pudb/
  mklink $DOTTY_CONFIG_HOME/dev/python/.* ~/
}

clean() {
  rm -rf $HOME/.miniconda
  for f in $(echo $DOTTY_CONFIG_HOME/dev/python/.*); do
    rm -f ~/${f##*/}
  done
  for f in $(echo $DOTTY_CONFIG_HOME/dev/python/config/*); do
    rm -rf $XDG_CONFIG_HOME/${f##*/}
  done
}

init "$@"
