#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  brew install python pyenv

  python3 -m pip install --user --upgrade pip setuptools pipenv

  # Other packages
  python3 -m pip install --user --upgrade pylint yapf autoflake gnureadline black grip cpplint

}

update() {
  python3 -m pip install --user --upgrade pip setuptools pipenv
}

link() {
  mklink config/flake8 $XDG_CONFIG_HOME/
  mklink config/pudb/pudb.cfg $XDG_CONFIG_HOME/pudb/
  mklink .* ~/
}

clean() {
  rm -fv $XDG_CONFIG_HOME/flake8 $XDG_CONFIG_HOME/pudb
}

init "$@"
