#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source ${0:A:h}/env.zsh

install() {
  # Install Xcode command line tools
  xcode-select --install

  # Install homebrew
  if ! _is_callable brew; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  brew install wget curl git tree coreutils bash gnupg2 p7zip ripgrep fd jq

  brew tap buo/cask-upgrade # Upgrade with `brew cu`

  # mac quicklook https://github.com/sindresorhus/quick-look-plugins
  brew install qlcolorcode qlstephen qlmarkdown quicklook-json qlimagesize qlvideo

  brew install --cask karabiner-elements rectangle

  # Fonts
  brew tap homebrew/cask-fonts
  brew install --cask font-ubuntu-mono-nerd-font font-fira-code-nerd-font

  # Download app from anywhere
  sudo spctl --master-disable
  # Remove the Dock autohide animation
  defaults write com.apple.dock autohide-time-modifier -int 0
  killall Dock

  # Enable ssh X11 forwarding. Disabled now due to the pool usability
  # brew install --cask xquartz
  # defaults write org.macosforge.xquartz.X11 enable_iglx -bool true
}

update() {
  if _is_callable brew; then
    brew update && brew upgrade && brew cleanup
  else
    echo-fail "homebrew not detected"
  fi

  brew cu
}

link() {
  mklink Library/Keybindings/* $HOME/Library/

  # Sync karabiner config. It deos not allow symlink.
  mkdir -p $XDG_CONFIG_HOME/karabiner/
  cp -f ${0:A:h}/config/karabiner/karabiner.json $XDG_CONFIG_HOME/karabiner/karabiner.json
  # If you change the karabiner config, copy it back and push a commit
  # cp -f $XDG_CONFIG_HOME/karabiner/karabiner.json ${0:A:h}/config/karabiner/karabiner.json

  # Copy fonts
  mkdir -p ~/Library/Fonts
  fd ".*\.(ttf|otf)" "$DOTFILES/assets/fonts/general" --print0 | xargs -0 -n 1 -I{} rsync -a --ignore-existing "{}" ~/Library/Fonts

  # Create wgetrc
  [[ ! -f $WGETRC ]] && touch $WGETRC
}

# clean() {}

init "$@"
