#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  # Download app from anywhere
  sudo spctl --master-disable

  brew install gcc coreutils duti

  brew tap buo/cask-upgrade # Upgrade with `brew cu`

  brew install --cask karabiner-elements raycast monitorcontrol

  # Fonts
  brew tap homebrew/cask-fonts
  brew install --cask font-maple-mono-normal-nf font-ubuntu-mono-nerd-font

  # Remove the Dock autohide animation
  defaults write com.apple.dock autohide-time-modifier -int 0
  killall Dock

  # Enable ssh X11 forwarding. Disabled now due to the pool usability
  # brew install --cask xquartz
  # defaults write org.macosforge.xquartz.X11 enable_iglx -bool true

  # Add some recommendation
  echo-info "Recommended to set 'Remove items from the Trash after 30 days' in Finder->Preference->Advanced"
  echo-info "Recommended to set 'Show all filename extensions' in Finder->Preference->Advanced"
  echo-info "Recommended to set default view in Finder->View->Show View Options(CMD-j),
e.g. Always open in list view, group by kind, sort by name. Click 'Use as defaults'.
Close all finder windows. Then run \`sudo find / -name .DS_Store -delete &>/dev/null | echo; killall Finder\`"
}

update() {
  if _is_callable brew; then
    brew update && brew upgrade && brew cleanup
  else
    echo-fail "homebrew not detected"
  fi

  brew cu
}

link() {
  # Sync karabiner config. It deos not allow symlink.
  mkdir -p $XDG_CONFIG_HOME/karabiner/
  cp -f $DOTTY_CONFIG_HOME/base/macos/config/karabiner/karabiner.json $XDG_CONFIG_HOME/karabiner/karabiner.json
  # If you change the karabiner config, copy it back and push a commit
  # cp -f $XDG_CONFIG_HOME/karabiner/karabiner.json $DOTTY_CONFIG_HOME/base/macos/config/karabiner/karabiner.json

  # Copy fonts
  mkdir -p ~/Library/Fonts
  [[ -d ${DOTTY_ASSETS_HOME}/fonts ]] && find "$DOTTY_ASSETS_HOME/fonts/general" -iname "*.ttf" -or -iname "*.otf" -print0 |
    xargs -0 -n 1 -I{} rsync -a --ignore-existing "{}" ~/Library/Fonts
}

# clean() {}

init "$@"
