#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  brew install phpenv php-build libmcrypt
}

update() {
  brew upgrade phpenv php-build libmcrypt
}

# link() { }

# clean() { }

init "$@"
