#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  topic-enabled-p dev/rust || ${0:A:h}/../../deploy dev/rust

  cargo install --git https://github.com/kamiyaa/joshuto.git
}

# update() {}

link() {
  mklink config/* $XDG_CONFIG_HOME/
}

clean() {
  rm -rv $XDG_CONFIG_HOME/joshuto

  cargo uninstall joshuto
}

init "$@"
