#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  # Deploy rust if not yet deployed
  ! topic-enabled-p dev/rust && dotty dev/rust

  cargo install --git https://github.com/kamiyaa/joshuto.git
}

# update() {}

link() {
  mklink $DOTTY_CONFIG_HOME/shell/joshuto/config/* $XDG_CONFIG_HOME/
}

clean() {
  rm -rv $XDG_CONFIG_HOME/joshuto

  cargo uninstall joshuto
}

init "$@"
