#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install bash
}

# update() { }

link() {
  mklink $DOTTY_CONFIG_HOME/shell/bash/.bash* ~/
}

clean() {
  rm -fv ~/.bash{rc,_profile}
}

init "$@"
