#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
  macos)
    rm -r /Applications/Emacs.app

    brew tap d12frosted/emacs-plus
    brew install emacs-plus@28 --with-native-comp
    ln -Fs $(sudo find /usr/local/Cellar/emacs-* -name "Emacs.app") /Applications/Emacs.app

    # Other tweaks
    defaults write org.gnu.Emacs Emacs.ToolBar -string no
    defaults write org.gnu.Emacs Emacs.ScrollBar -string no
    defaults write org.gnu.Emacs Emacs.MenuBar -string no
    ;;
  linux-*)
    brew install emacs
    ;;
  esac

  # Clone Doom Eemacs
  rm -rfv $XDG_CONFIG_HOME/emacs
  git clone https://github.com/hlissner/doom-emacs -b develop $XDG_CONFIG_HOME/emacs

  # Clone my config
  rm -rfv $XDG_CONFIG_HOME/doom
  git clone https://github.com/ztlevi/doom-config $XDG_CONFIG_HOME/doom

  cd $XDG_CONFIG_HOME/emacs
  $XDG_CONFIG_HOME/emacs/bin/doom install
}

update() {
  doom upgarde
}

link() {
  mklink .ctags ~/.ctags
}

clean() {
  rm -rfv $XDG_CONFIG_HOME/doom
  rm -rfv $XDG_CONFIG_HOME/emacs
}

init "$@"
