#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
  macos)
    rm -r /Applications/Emacs.app
    brew tap railwaycat/emacsmacport
    brew install --cask emacs-mac
    # Other tweaks
    defaults write org.gnu.Emacs Emacs.ToolBar -string no
    defaults write org.gnu.Emacs Emacs.ScrollBar -string no
    defaults write org.gnu.Emacs Emacs.MenuBar -string no
    ;;
  linux-*)
    brew install emacs
    ;;
  esac

  # Clone Doom Eemacs
  rm -rfv $XDG_CONFIG_HOME/emacs.d
  git clone https://github.com/hlissner/doom-emacs -b develop $XDG_CONFIG_HOME/emacs.d

  # Clone my config
  rm -rfv $XDG_CONFIG_HOME/doom.d
  git clone https://github.com/ztlevi/doom-config $XDG_CONFIG_HOME/doom.d

  cd $XDG_CONFIG_HOME/emacs.d
  $XDG_CONFIG_HOME/emacs.d/bin/doom install
}

update() {
  doom upgarde
}

link() {
  [[ -d $XDG_CONFIG_HOME/doom.d ]] && mv $XDG_CONFIG_HOME/doom.d $XDG_CONFIG_HOME/doom
  if [[ -d $XDG_CONFIG_HOME/emacs.d ]]; then
    rm -rf $XDG_CONFIG_HOME/emacs.d/.local
    mv $XDG_CONFIG_HOME/emacs.d $XDG_CONFIG_HOME/emacs
  fi
  mklink .ctags ~/.ctags
}

clean() {
  rm -rfv $XDG_CONFIG_HOME/doom.d
  rm -rfv $XDG_CONFIG_HOME/emacs.d
}

init "$@"
