#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install ranger
}

# update() {}

link() {
  mklink config/* $XDG_CONFIG_HOME/
}

clean() {
  rm -rv $XDG_CONFIG_HOME/ranger

  brew uninstall ranger
}

init "$@"
