#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install ranger atool
}

# update() {}

link() {
  rm -rf $XDG_CONFIG_HOME/ranger
  mklink $DOTTY_CONFIG_HOME/shell/ranger/config/* $XDG_CONFIG_HOME/
}

clean() {
  rm -rv $XDG_CONFIG_HOME/ranger

  brew uninstall ranger
}

init "$@"
