#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
  macos)
    brew install --cask basictex
    sudo tlmgr update --self
    sudo tlmgr install latexmk multirow
    ;;
  arch) yay --needed --noconfirm texlive-most texlive-lang ;;
  debian) $APT_INSTALL texlive-full ;;
  esac

}

# update() {}

# link() {}

# clean() {}

init "$@"
