#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
  macos)
    brew install --cask basictex
    sudo tlmgr update --self
    sudo tlmgr install latexmk multirow
    ;;
  linux-debian) $APT_INSTALL texlive-full ;;
  linux-RHEL)
    # TODO: add RHEL tex packages
    ;;
  esac

}

# update() {}

# link() {}

# clean() {}

init "$@"
