#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  case $(_os) in
  macos | debian)
    brew install fzf
    ;;
  arch)
    yay --needed --noconfirm -S fzf
    ;;
  esac
}

# update() {}

# link() {}

clean() {
  rm -rf $XDG_DATA_HOME/fzf
}

init "$@"
