#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  brew install fzf
  rm -f ~/.fzf.{bash,zsh}
}

# update() {}

# link() {}

clean() {
  rm -rf $XDG_DATA_HOME/fzf
}

init "$@"
