#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
    macos)
      brew install --cask nikitabobko/tap/aerospace

      #  Now, you can move windows by holding `ctrl+cmd` and dragging any part of
      #  the window (not necessarily the window title)
      defaults write -g NSWindowShouldDragOnGesture -bool true

      # https://nikitabobko.github.io/AeroSpace/guide#a-note-on-mission-control
      defaults write com.apple.dock expose-group-apps -bool true && killall Dock

      # https://nikitabobko.github.io/AeroSpace/guide#a-note-on-displays-have-separate-spaces
      defaults write com.apple.spaces spans-displays -bool true && killall SystemUIServer
      ;;

  esac

}

# update() {}

link() {
  mklink $DOTTY_CONFIG_HOME/wm/aerospace/config/* $XDG_CONFIG_HOME/
  _is_callable aerospace && aerospace reload-config

}

clean() {
  rm -fv $XDG_CONFIG_HOME/aerospace
}

init "$@"
