#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  case $(_os) in
    macos)
      brew install --cask nikitabobko/tap/aerospace

      # TODO: is this useful?
      #  Now, you can move windows by holding `ctrl+cmd` and dragging any part of
      #  the window (not necessarily the window title)
      defaults write -g NSWindowShouldDragOnGesture -bool true
      ;;

  esac

}

# update() {}

link() {
  mklink $DOTTY_CONFIG_HOME/wm/aerospace/config/* $XDG_CONFIG_HOME/
}

clean() {
  rm -fv $XDG_CONFIG_HOME/aerospace
}

init "$@"
