#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  # https://aider.chat/docs/install.html
  brew install uv
  uv tool install --force --python python3.12 aider-chat@latest
  uv tool run --from aider-chat pip install boto3
}

# update() {}

link() {
  mklink $DOTTY_CONFIG_HOME/misc/ai/config/aider.conf.yml ~/.aider.conf.yml
  mklink $DOTTY_CONFIG_HOME/misc/ai/config/aider.model.settings.yml ~/.aider.model.settings.yml
  mkdir -p ~/.aws/amazonq
  mklink $DOTTY_CONFIG_HOME/misc/ai/config/mcp.json ~/.aws/amazonq/mcp.json
}

clean() {
  rm -f ~/.aider.conf.yml
}

init "$@"
