#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install gh
  case $(_os) in
    macos)
      # brew install --cask claude-code
      ;;
    linux*)
      # curl -fsSL https://claude.ai/install.sh | bash
      ;;
  esac

  ! topic-enabled-p dev/node && dotty dev/node

  # Install skills
  gh extension install ai-ecoverse/gh-upskill
  gh upskill -g anthropics/skills --skill pdf --skill xlsx
  gh upskill -g ogulcancelik/herdr --skill herdr
  gh upskill -g yizhiyanhua-ai/fireworks-tech-graph --skill fireworks-tech-graph
}

update() {
  brew upgrade gh
  gh extension upgrade upskill
}

link() {
  mkdir -p ~/.claude
  mklink $DOTTY_CONFIG_HOME/misc/ai/claude/* ~/.claude/

  mkdir -p ~/.kiro/settings
  mklink $DOTTY_CONFIG_HOME/misc/ai/config/mcp.json ~/.kiro/settings/mcp.json
  mklink $DOTTY_CONFIG_HOME/misc/ai/kiro/agents/* ~/.kiro/agents/
  mklink $DOTTY_CONFIG_HOME/misc/ai/kiro/settings/* ~/.kiro/settings/
}

clean() {
}

init "$@"
