#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  # https://aider.chat/docs/install.html
  brew install uv
  uv tool install --force --python python3.12 aider-chat@latest
  uv tool run --from pip pip install boto3
}

# update() {}

link() {
  mklink $DOTTY_CONFIG_HOME/misc/ai/config/aider.conf.yml ~/.aider.conf.yml
}

clean() {
  rm -f ~/.aider.conf.yml
}

init "$@"
