#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
GIT_DIR="$XDG_CONFIG_HOME/git"

install() {
  brew install git libressl openssl git-lfs gh diff-so-fancy git-extras git-flow-avh
  case $(_os) in
  macos)
    brew tap microsoft/git
    brew install --cask git-credential-manager-core
    ;;
  linux-*)
    brew install pass
    if [[ ! -f $HOME/.local/share/password-store/.gpg-id ]]; then
      pass init ztlevi.work@gmail.com
    fi

    local tempdir=/tmp/temp-install
    mkdir -p $tempdir
    (
      cd $tempdir
      wget --no-check-certificate \
        $(get_github_latest_release_url microsoft/Git-Credential-Manager-Core .tar.gz) -O gcm.tar.gz
      sudo tar -xvf gcm.tar.gz -C /usr/local/bin
      rm -f gcm.tar.gz
    )
    ;;
  esac
}

# update() {}

link() {
  rm -fv ~/.gitconfig $GIT_DIR/config
  mklink $DOTTY_CONFIG_HOME/shell/git/config $GIT_DIR/
  mklink $DOTTY_CONFIG_HOME/shell/git/ignore $GIT_DIR/
  mklink $DOTTY_CONFIG_HOME/shell/git/.ignore ~/
}

clean() {
  rm -rf $GIT_DIR
}

init "$@"
