#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source ${0:A:h}/../../env
GIT_DIR="$XDG_CONFIG_HOME/git"

install() {
  brew install git git-lfs gh diff-so-fancy git-standup git-extras git-flow-avh
  case $(_os) in
  macos)
    brew tap microsoft/git
    brew install --cask git-credential-manager-core
    ;;
  linux-*)
    brew install pass
    local tempdir=/tmp/temp-install
    mkdir -p $tempdir
    (
      cd $tempdir
      wget --no-check-certificate \
        $(get_github_latest_release_url microsoft/Git-Credential-Manager-Core .tar.gz) -O gcm.tar.gz
      sudo tar -xvf gcm.tar.gz -C /usr/local/bin
      rm -f gcm.tar.gz
    )
    ;;
  esac
}

# update() {}

link() {
  rm -fv ~/.gitconfig $GIT_DIR/config
  mklink config $GIT_DIR/
  mklink ignore $GIT_DIR/
}

clean() {
  rm -rfv $GIT_DIR
}

init "$@"
