#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source $DOTTY_CONFIG_HOME/shell/zsh/.zshenv

install() {
  # Base utilities
  brew install zsh bash wget git curl tree rsync p7zip jq direnv

  # Use trash instead of rm
  case $(_os) in
    linux-*) brew install trash-cli;;
    macos) brew install trash;;
  esac

  # Better console tools
  brew install exa ripgrep fd bat hyperfine

  # Other utilities
  brew install shfmt zshdb bashdb procs dust shellcheck neofetch mosh \
    sd duf

  # True color and Italic support https://github.com/syl20bnr/spacemacs/wiki/Terminal
  if _is_callable /usr/bin/tic; then
      /usr/bin/tic -x -o ~/.terminfo $DOTTY_CONFIG_HOME/shell/zsh/xterm-24bit.terminfo
  else
      echo-fail "/usr/bin/tic does not exists\!"
  fi

  # Set default shell to zsh
  chsh -s $(which zsh) $(whoami)
  # if the command above doesn't work, edit /etc/passwd directly to change the login shell

  local zsh="$(which zsh)"
  grep $zsh /etc/shells &>/dev/null || sudo tee -a /etc/shells <<<$zsh
}

update() {
  echo-info "zinit self-update"
  echo-info "zinit update --parallel"
}

link() {
  rm -rf ~/.zinit/snippets/*.config--*--config--shell--zsh
  rm -f ~/.profile
  mklink $DOTTY_CONFIG_HOME/shell/zsh/.zsh* ~/
  mklink $DOTTY_CONFIG_HOME/shell/zsh/.p10k.zsh ~/
  mklink $DOTTY_CONFIG_HOME/shell/zsh/config/* $XDG_CONFIG_HOME/
  mklink $DOTTY_CONFIG_HOME/shell/zsh/completions $XDG_CONFIG_HOME/zsh/

  # Create wgetrc
  [[ ! -f $WGETRC ]] && touch $WGETRC
}

clean() {
  rm -f ~/.zshrc
  rm -f ~/.zshenv
  rm -f $XDG_CONFIG_HOME/starship.toml
}

init "$@"
