#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  # These packages are nice to have but unfortunately alacritty doesn't
  # support inline image protocol
  # video preview: ffmpegthumbnailer
  # pdf preview: poppler
  # cd jump: zoxide
  brew install yazi unar jq
}

# update() {}

link() {
  mklink $DOTTY_CONFIG_HOME/shell/yazi/config/* $XDG_CONFIG_HOME/
}

clean() {
  rm -rv $XDG_CONFIG_HOME/yazi
  brew uninstall yazi
}

init "$@"
