#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  brew install nodenv node-build

  nodenv install $NODE_VERSION
  nodenv global $NODE_VERSION

  # NPM Packages
  npm install -g npm yarn prettier live-server hexo-cli \
    reveal-md typescript tslint cspell typescript-language-server
}

update() {
  brew upgrade nodenv node-build
  npm update -g
}

link() {
  mklink .* ~/
}

clean() {
  rm -rf $NODENV_ROOT
}

init "$@"
