#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install nodenv node-build

  nodenv install $NODE_VERSION
  nodenv global $NODE_VERSION

  path=($NODENV_ROOT/shims $path)
  # NPM Packages
  npm install -g npm pnpm typescript tslint typescript-language-server
  # Run rehash everytime install global package
  nodenv rehash
}

update() {
  brew upgrade nodenv node-build
  npm update -g
}

link() {
  mklink $DOTTY_CONFIG_HOME/dev/node/.* ~/
}

clean() {
  for f in $(echo $DOTTY_CONFIG_HOME/dev/node/.*); do
    rm -f ~/${f##*/}
  done
  rm -rf $NODENV_ROOT
  rm -f $XDG_CACHE_HOME/${SHELL##*/}/nodenv
}

init "$@"
