#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  # For local node version, create .nvmrc file and do `nvm use`
  brew install nvm
  nvm install --lts
  nvm use --lts

  # NPM Packages
  npm install -g npm pnpm typescript typescript-language-server
}

update() {
  brew upgrade nvm
  npm update -g
}

link() {
  # do not use nvm as system node
  rm -f $HOME/.nvm/alias/default
  mklink $DOTTY_CONFIG_HOME/dev/node/.* ~/
}

clean() {
  for f in $(echo $DOTTY_CONFIG_HOME/dev/node/.*); do
    rm -f ~/${f##*/}
  done
  rm -rf $HOME/.nvm
}

init "$@"
