#!/usr/bin/env zsh
# ASCII text
# http://patorjk.com/software/taag/#p=display&f=Broadway&t=gnome

DOTTY_HOME=${HOME}/.dotty
DESKTOP=${DOTTY_HOME}/desktop/general

source ${DOTTY_HOME}/env

export GTK2_RC_FILES=${XDG_CONFIG_HOME}/gtk-2.0

# xrandr --output DisplayPort-0 --primary --auto  --output DisplayPort-1 --auto --right-of DisplayPort-0 --dpi 144
RESOLUTION=$(xrandr -q | grep primary | grep ' connected' | cut -d' ' -f4 | cut -d 'x' -f1)
if [ -z ${RESOLUTION} ]; then RESOLUTION=1920; fi

SCREEN_SCALE=$((${RESOLUTION} / 1920))

[[ -f ${DESKTOP}/Xresources ]] && xrdb -merge ${DESKTOP}/Xresources
[ "${SCREEN_SCALE}" -eq 2 ] && [[ -f ${DESKTOP}/Xresources_4K ]] && xrdb -merge ${DESKTOP}/Xresources_4K

# AWESOME
if echo ${XDG_SESSION_DESKTOP} | grep -qi "awesome"; then
  export GDK_SCALE=${SCREEN_SCALE}
  export QT_AUTO_SCREEN_SCALE_FACTOR=1

  # revert gnome screen scale settings
  _call gsettings set org.gnome.desktop.interface scaling-factor 1

  if ((SCREEN_SCALE >= 2)); then
    _call xrandr --dpi 150
  fi

# BSPWM
elif echo ${XDG_SESSION_DESKTOP} | grep -qi "bspwm"; then
  export GDK_SCALE=${SCREEN_SCALE}
  export QT_AUTO_SCREEN_SCALE_FACTOR=0
  export QT_SCALE_FACTOR=${GDK_SCALE}

  # revert gnome screen scale settings
  _call gsettings set org.gnome.desktop.interface scaling-factor 1

# GNOME
elif echo ${XDG_SESSION_DESKTOP} | grep -qi "gnome"; then
  export GDK_SCALE=1
  export QT_AUTO_SCREEN_SCALE_FACTOR=1
  export QT_SCALE_FACTOR=1

  # Adjust gnome scaling factor based on monitor resolution, might need restart for gnome
  _call gsettings set org.gnome.desktop.interface scaling-factor ${SCREEN_SCALE}
fi

# autostart programs
{
  if _is_callable gnome-keyring-daemon; then
    eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
    export SSH_AUTH_SOCK
  fi

  # OS specific apps
  case $(_os) in
  linux-arch)
    # Manjaro linux fix add/remove software auth issue
    _call /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
    ;;
  esac

  _run fcitx -d &

  # non-essentials
  {
    sleep 1
    _run redshift &         # screen temperature based on time-of-day
    _run greenclip daemon & # system wide clipboard
    # _run mpd &      # music server
    # _run rslsync &  # resilio sync

    sleep 1
    [[ -e ${DOTTY_HOME}/desktop/general/xprofile_local ]] && zsh ${DOTTY_HOME}/desktop/general/xprofile_local
  } &
} 2>&1 >${XDG_DATA_HOME}/xsession-errors.log
