#!/usr/bin/env zsh
source ${0:A:h}/../../deploy
source env.zsh

install() {
  # TODO Install android SDK
  case $(_os) in
  macos)
    brew tap adoptopenjdk/openjdk
    brew install --cask adoptopenjdk8 adoptopenjdk11
    ;;
  linux-debian)
    sudo apt install openjdk-8-jdk
    # Installation for newer version of java on debian OS
    # sudo add-apt-repository ppa:webupd8team/java
    # sudo apt-get update
    # $APT_INSTALL oracle-java12-installer
    # $APT_INSTALL oracle-java12-set-default
    ;;
  linux-RHEL)
    sudo yum install java-1.8.0-openjdk java-1.8.0-openjdk-devel
    _is_callable amazon-linux-extras && sudo amazon-linux-extras install java-openjdk11
    ;;
  esac
  brew install gradle maven
}

# update() {}

# link() {}

# clean() {}

init "$@"
