#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install weechat

  # NOTE: init.sh needs to be run separately, afterward
  echo "Don't forget to run weechat/scripts/bootstrap.sh while weechat is open"
}

# update() {}

# link() {}

# clean() {}

init "$@"
