#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install gnupg
  if [[ $(_os) == "macos" ]]; then
    brew install gpg-suite
  fi
}

# update() {}

link() {
  rm -f $HOME/.gnupg/gpg-agent.conf
  mkdir -p $HOME/.gnupg && chmod 700 $HOME/.gnupg
  cat <<EOF >$HOME/.gnupg/gpg-agent.conf
default-cache-ttl 86400
max-cache-ttl 1036800
default-cache-ttl-ssh 86400
max-cache-ttl-ssh 1036800
EOF
  case $(_os) in
  macos)
    cat <<EOF >>$HOME/.gnupg/gpg-agent.conf
pinentry-program /usr/local/MacGPG2/libexec/pinentry-mac.app/Contents/MacOS/pinentry-mac
EOF
    ;;
  esac
  # Restart gpg
  # gpgconf --kill gpg-agent
}

# clean() {}

init "$@"
