#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

install() {
  brew install gnupg
  if [[ $(_os) == "macos" ]]; then
    brew install pinentry-mac
  fi
}

# update() {}

link() {
  rm -f $HOME/.gnupg/gpg-agent.conf
  mkdir -p $HOME/.gnupg && chmod 700 $HOME/.gnupg
  cat <<EOF >$HOME/.gnupg/gpg-agent.conf
default-cache-ttl 604800
max-cache-ttl 604800
EOF
  case $(_os) in
  macos)
    cat <<EOF >>$HOME/.gnupg/gpg-agent.conf
pinentry-program /usr/local/bin/pinentry-mac
EOF
    ;;
  esac
  # Restart gpg
  # gpgconf --kill gpg-agent
}

# clean() {}

init "$@"
