#!/usr/bin/env zsh
source ${0:A:h}/../../deploy

# install() {}

# update() {}

link() {
  if [[ -d $HOME/workplace/work ]]; then
    mklink $HOME/workplace/work $HOME/.work
  fi
  if [[ ! -d $HOME/.work/dots ]]; then
    mkdir -p $HOME/.work/dots
    touch $HOME/.work/dots/aliases.zsh
    touch $HOME/.work/dots/env.zsh
  fi
}

# clean() {}

init "$@"
